name: logiscout-rag-server

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=.docker-buildx-cache
      cache_to:
        - type=local,dest=.docker-buildx-cache,mode=max
    image: logiscout-rag-server:latest
    container_name: logiscout-rag-api
    working_dir: /app
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      FASTEMBED_CACHE_PATH: /app/.cache/fastembed
    volumes:
      - fastembed_cache:/app/.cache/fastembed
      - ./logs:/app/logs

volumes:
  fastembed_cache:
