name: logiscout-rag-server

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: logiscout-rag-server:latest
    container_name: logiscout-rag-api
    working_dir: /app
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      HF_HOME: /app/.cache/huggingface
    volumes:
      - hf_cache:/app/.cache/huggingface
      - ./logs:/app/logs

volumes:
  hf_cache:
